name: Checkout
on: [push]

jobs:

    checkout-with-action:
      runs-on: ubuntu-latest
      steps:
        - name: files before
          run: ls -a
        - name: Checkout
          uses: actions/checkout@v3
        - name: files before
          run: ls -a

    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main 
            - name: List Files after
              run: ls -a