name: Matrix workflow
on:
  workflow_dispatch:
    inputs:
      os: 
        description: Operating Systems
        default: "windows-latest,ubuntu-latest"
        type: string
      node-version:
        description: Node version
        default: "14,16,18"
        type: string
jobs:

  prepare-matrix:
    runs-on: ubuntu-latest
    outputs: 
      matrix-arrays: ${{steps.matrix-arrays.outputs.result}}
    steps:
      - uses: actions/github-script@v6
        id: matrix-arrays
        with: 
          script: |
            const os = context.payload.inputs['os'].split(',');
            const nodeVersion = context.payload.inputs['node-version'].split(',');
            return { os, 'node-version': nodeVersion };
          result-encoding: json
      - run: echo '${{steps.matrix-arrays.outputs.result}}'
      - run: echo "step-output=value" >> $GITHUB_ENV
        id: step-1
      - run: echo "step-output=value 2" >> $GITHUB_ENV
        id: step-2
      - run: |
          echo "${{ steps.step-1.outputs.step-output }}"
          echo "${{ steps.step-2.outputs.step-output }}"
      
      

  node-matrix:
    continue-on-error: true
    needs: prepare-matrix
    strategy:
        matrix:
            os: ${{fromJson(needs.prepare-matrix.outputs.matrix-arrays).os}}
            node-version: ${{fromJson(needs.prepare-matrix.outputs.matrix-arrays).node-version}}
        fail-fast: false
    runs-on: ${{matrix.os}}
    steps: 
        - run: node -v
        - uses: actions/setup-node@v3
          with:  
            node-version: 13
        - run: node -v
