name: Matrix workflow
on: [push]

jobs:
  node-matrix:
    continue-on-error: true
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [12.x, 14.x, 16.x]
        # max-parallel: 3
        fail-fast: false
    runs-on: ${{matrix.os}}
    steps: 
        - run: node -v
        - uses: actions/setup-node@v3
          with:  
            node-version: 13
        - run: echo ${{matrix}}
