name: Reusable workflow caller
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Workflow name"
        required: true
        type: string
        default: "kartik"

jobs:
  calling-a-reusable-wf:
    uses: github-action-course-1/workflows/.github/workflows/trigger.yaml@main
    with:
      name: ${{github.event.inputs.name}}
    secrets:
      access-token: ${{secrets.ACCESS_TOKEN}}
  calling-a-reusable-in-same-repo:
    uses: github-action-course-1/course-code/.github/workflows/using-reusable-workflow.yaml@main
  using-reusable-workflow:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-in-same-repo
    steps:
      - run: echo ${{needs.calling-a-reusable-in-same-repo.outputs.date}}
