name: Status check functions
on: [push]

jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
        - name: step1
          run: sleep 10
        - name: step2
          id: step-2
          run: exit 1
        - name: runs on failure
          if: failure() && steps.step-2.conclusion=='failure'
          run: echo 'runs only on failure'
        - name: runs on success
          if: success()
          run: echo 'runs only on success'
        - name: Always runs
        #   if: success() || failure()
          if: always()
          run: echo 'always runs'
        - name: runs whrn cancelled
          if: cancelled()
          run: echo 'runs only on cancelled'



  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps: 
      - run: echo 'jobs 2'
    