name: Reusable workflow
on: 
  workflow_call:
    outputs:
        date:
            description: 'The date' 
            value: ${{jobs.generate-output.outputs.date}}

jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
        date: ${{steps.date-step.outputs.date}}
    steps:
      - name: Generate Date
        id: date-step
        run: echo "date=$(date)" >> $GITHUB_ENV
