name: workflow commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Settting an error message
              run: echo "::error::Missing semicolon in command"
            - name: setting an error message with params
              run: echo "::debug title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: setting a warning message with params
              run: echo "::warning title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: setting a notice message with params
              run: echo "::notice title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
            - name: grouping
              run: |
                echo "::group:: My group title"
                echo "inside group"
                echo "::notice title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
                echo "::warning title=error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing semicolon"
                echo "::endgroup::"
            - name: Masking a value
              run: echo "::add-mask::Secret String"
            - name: Echo secret
              run: echo "Secret String"
  