name: Workflow run
on: 
  workflow_run:
    workflows: [Repository Events]  
    types: [completed]
    branches: 
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "i was triggerd bcz of other repo event"