name: Working Dirs & Shells
on: [push]
defaults:
  run: 
    shell: bash
    # working-directory: /home/runner/work/github-actions/github-actions

jobs: 
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display currentworing dir & list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: change working directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run: 
        shell: pwsh
    steps:
      - name: Display currentworing dir & list files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE

      - name : display
        shell: python
        run : |
          import platform
          print(platform.system())
